query Game($id: ID!){
    game(where: {
            id: $id
    }) {
        id
        scan {
            id
            name
            description
            questions{
                id
            }
        }
    }
}