query Player($id: ID!){
    player(where: {
        id: $id
    }){
        createdAt
        id
        name
        points
        avatar
        game {
            scan {
                name
                description
            }
        }
        questionsAnswered{
            id
        }
    }
}
