query Scan($id: ID!){
    scan(where: {
        id: $id
    }) {
        id
        name
        questions {
            id
            question
            type
            proposals
            answer
        }
        user{
            id
        }
    }
}